name: release-please

on:
  # Manually trigger the release process for a specific package
  workflow_dispatch:
    inputs:
      package-folder:
        description: 'The package to be released'
        required: true
        type: choice
        options:
          - pckg-a
          - pckg-b
          # - pckg-c
          # - pckg-d
  push:
    # Creates a release & tag when a PR is merged into main
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  # Sequential release jobs for each package, respecting dependencies
  release-pckg-a:
    runs-on: ubuntu-24.04
    steps:
      - name: Release pckg-a
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          path: packages/pckg-a

  release-pckg-b:
    needs: release-pckg-a
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Release pckg-b
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          path: packages/pckg-b

  # release-pckg-c:
  #   needs: release-pckg-b
  #   if: github.event_name == 'workflow_dispatch' &&
  #     (github.event.inputs.package-folder == 'pckg-c' ||
  #     github.event.inputs.package-folder == 'pckg-d')
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Release pckg-c
  #       uses: googleapis/release-please-action@v4
  #       with:
  #         token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
  #         path: packages/pckg-c

  # release-pckg-d:
  #   needs: release-pckg-c
  #   if: github.event_name == 'workflow_dispatch' &&
  #     github.event.inputs.package-folder == 'pckg-d'
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Remove devDependencies from package.json
  #       run: |
  #         cd packages/pckg-d
  #         mv package.json package.json.bak
  #         node <<- EOM
  #           const fs = require("fs");
  #           const pkg = JSON.parse(fs.readFileSync("package.json.bak", {encoding: "utf8"}));
  #           pkg.devDependencies = {};
  #           fs.writeFileSync("package.json", JSON.stringify(pkg, null, "\t"), {encoding: "utf8"});
  #         EOM
  #     - name: Release pckg-d
  #       uses: googleapis/release-please-action@v4
  #       with:
  #         token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
  #         path: packages/pckg-d