name: release-please-create-pr

on:
  # Manually trigger the release process for a specific package
  workflow_dispatch:
    inputs:
      do_prs:
        description: "Create PRs for packages"
        default: true
        required: false
        type: boolean

  push:
    # Creates a release & tag when a PR is merged into main
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-packages:
    runs-on: ubuntu-24.04
    steps:
      - name: Create PRs for packages
        uses: googleapis/release-please-action@v4
        id: release_please
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
