name: release-please

on:
  # Manually trigger the release process for a specific package
  workflow_dispatch:
    inputs:
      package-folder:
        description: "Manual trigger release"
  push:
    # Creates a release & tag when a PR is merged into main
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Release Please Checks
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}